name: Release and Publish
on:
  push:
    branches:
      - main
permissions:
  contents: write
  pull-requests: write
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Release Please
        id: release
        uses: googleapis/release-please-action@v5
        with:
          release-type: node
      - name: Checkout
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/checkout@v6
      - name: Setup pnpm
        if: ${{ steps.release.outputs.release_created }}
        uses: pnpm/action-setup@v6
        with:
          version: 10
      - name: Setup Node.js
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/setup-node@v6
        with:
          node-version: '22'
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies
        if: ${{ steps.release.outputs.release_created }}
        run: pnpm install --frozen-lockfile
      - name: Build SvelteKit Library
        if: ${{ steps.release.outputs.release_created }}
        run: pnpm run pack
      - name: Publish to NPM
        if: ${{ steps.release.outputs.release_created }}
        run: pnpm publish --no-git-checks --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
